vmid: 23002
proxmox_node: "n2"

proxmox_ostype: "l26"
proxmox_iso_filename: "ubuntu-24.04.4-live-server-amd64-autoinstall.iso"

cores: 1
memory_mb: 512
os_disk_gb: 10

# extra_disks:
#  - disk_gb: 50
#    pve_storage: "local-pve-rpool"
#    mount_path: "/media/example-data"
#    fs_type: "ext4"
#    mount_options: "defaults,nofail"

# enable_autoupdate: false

add_vpn_client_overlay_ipv4: "10.13.0.9"

add_admin_scripts_user: "networker"

# Optional DNS aliases
# These will be registered in Unbound DNS
# dns_aliases:
#   - "dns1.lan"
#   - "dhcp1.lan"

host_users:
  - name: "networker"
    description: "dhcp / dns service account"
    groups:
      - sudo
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICYIQ2DpOGZ7q8FwbYfuJvDzaO0LYE3qrrD5q7qb0pKD lars@co3d.eu"

# vault.yml:
# host_user_passwords:
#   networker: "SECRET_VALUE_HERE"
#
# add_vpn_client_config: |
#   SECRET_VALUE_HERE
