---
- name: Install Kea packages
  ansible.builtin.apt:
    name: "{{ add_kea_packages }}"
    state: present
    update_cache: true

- name: Enable and start Kea services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ add_kea_services }}"
  loop_control:
    label: "{{ item }}"
