---
set_vm_network_netplan_file: /etc/netplan/50-cloud-init.yaml
set_vm_network_prefix: "{{ autoinstall_vm_ipv4_prefix }}"
set_vm_network_gateway: "{{ autoinstall_vm_ipv4_gateway }}"
set_vm_network_nameservers: "{{ autoinstall_vm_ipv4_nameservers }}"
set_vm_network_address: "{{ ansible_host }}"
set_vm_network_interface_name: "{{ ansible_default_ipv4.interface }}"
