---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart systemd-resolved
  ansible.builtin.service:
    name: "{{ unbound_setup_resolved_service_name }}"
    state: restarted

- name: Restart Unbound
  ansible.builtin.service:
    name: "{{ unbound_setup_service_name }}"
    state: restarted
