---
all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: "{{ ansible_admin_ssh_private_key_file }}"

  children:
    proxmox:
      hosts:
        n2:
          ansible_host: 192.168.178.6
          dns_name: n2.pxe
        n5:
          ansible_host: 192.168.178.5
          dns_name: n5.pxe

    vm:
      hosts:
        restic1:
          ansible_host: 192.168.178.195
        netcontroller1:
          ansible_host: 192.168.178.193
        netcontroller2:
          ansible_host: 192.168.178.194

    kea:
      hosts: {}

    unbound:
      hosts:
        netcontroller1:
        netcontroller2:

    ubuntu_auto_update:
      hosts:
        netcontroller1:
        netcontroller2:
        restic1:
