---
homelab_dns_blocklist_sources:
  - "https://codeberg.org/hagezi/mirror2/raw/branch/main/dns-blocklists/rpz/multi.txt"
  - "https://codeberg.org/hagezi/mirror2/raw/branch/main/dns-blocklists/rpz/doh.txt"


homelab_dns_forward_servers:
  - "9.9.9.9"
  - "192.168.178.1"

homelab_dns_local_tld: "lan"

# Maps IP addresses to DNS aliases (names)
# Each IP can have multiple names/aliases
homelab_dns_records:
  "192.168.178.55":
    - "dockerhost1"
    - "immich"
    - "paperless"
    - "grafana"
  "10.13.0.3":
    - "gateway.vpn"
  "10.13.0.6":
    - "dockerhost1.vpn"
    - "immich.vpn"
    - "paperless.vpn"
    - "grafana.vpn"
