---
homelab_dns_blocklist_sources: []

homelab_dns_local_tld: "lan"
homelab_dns_records:
  - name: "dockerhost1"
    value: "192.168.178.55"
  - name: "gateway.vpn"
    value: "10.13.0.3"
  - name: "dockerhost1.vpn"
    value: "10.13.0.6"
