vmid: 22001
proxmox_node: "n2"
proxmox_replica_nodes:
  - "n5"

proxmox_ostype: "l26"
proxmox_iso_filename: "ubuntu-24.04.4-live-server-amd64-autoinstall.iso"

cores: 2
memory_mb: 2048
os_disk_gb: 20

extra_disks:
  - disk_gb: 700
    pve_storage: "local-pve-rpool"
    mount_path: "/media/backups"
    fs_type: "ext4"
    mount_options: "defaults,nofail"

# enable_autoupdate: false

dns_aliases:
  - "backup.lan"

add_restic_server_data_dir: "/media/backups/restic-data"
add_restic_server_listen_address: ":8000"
add_restic_server_service_user: "archivar"
add_restic_server_service_group: "archivar"

add_restic_retention_service_user: "archivar"
add_restic_retention_repositories:
  - user: "restic-server-test"
    repository: "repo1"
    enabled: true
    forget_args:
      - "--keep-within"
      - "2d"
      - "--keep-weekly"
      - "1"
      - "--prune"
  - user: "lc3win"
    repository: "d"
    enabled: true
    forget_args:
      - "--keep-within"
      - "14d"
      - "--keep-weekly"
      - "4"
      - "--keep-monthly"
      - "4"
      - "--prune"
  - user: "lc3win"
    repository: "documents"
    enabled: true
    forget_args:
      - "--keep-within"
      - "14d"
      - "--keep-weekly"
      - "4"
      - "--keep-monthly"
      - "4"
      - "--prune"
  - user: "lc3win"
    repository: "scans"
    enabled: true
    forget_args:
      - "--keep-within"
      - "14d"
      - "--keep-weekly"
      - "4"
      - "--keep-monthly"
      - "4"
      - "--prune"
  - user: "dockerhost2"
    repository: "paperless"
    enabled: true
    forget_args:
      - "--keep-within"
      - "14d"
      - "--keep-weekly"
      - "4"
      - "--keep-monthly"
      - "4"
      - "--prune"

add_rclone_service_user: "archivar"
add_rclone_service_group: "archivar"
add_rclone_source_path: "/media/backups/restic-data/"
add_rclone_remote_path: "pCloud:homelab-restic1"

add_admin_scripts_user: "archivar"

host_users:
  - name: "archivar"
    description: "backup storage service account"
    groups:
      - sudo
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICYIQ2DpOGZ7q8FwbYfuJvDzaO0LYE3qrrD5q7qb0pKD lars@co3d.eu"

# vault.yml:
# host_user_passwords:
#   archivar: "USER_PASSWORD_HERE"

# add_restic_server_htpasswd_entries:
#   - user: "backup-user-1"
#     password: "REST_SERVER_PASSWORD_HERE"
#   - user: "backup-user-2"
#     password: "REST_SERVER_PASSWORD_HERE"

# add_restic_retention_repository_passwords:
#   "backup-user-1/repo1": "RESTIC_REPO_PASSWORD"

# add_rclone_remote_config_content: |
#   [pCloud]
#   type = pcloud
#   token = {"access_token":"...","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}
#   hostname = eapi.pcloud.com
