vmid: 22012
proxmox_node: "n2"
proxmox_replica_nodes:
  - "n5"

proxmox_ostype: "l26"
proxmox_iso_filename: "ubuntu-24.04.4-live-server-amd64-autoinstall.iso"

cores: 4
memory_mb: 4096
os_disk_gb: 40

extra_disks:
  - disk_gb: 20
    pve_storage: "local-pve-rpool"
    mount_path: "/media/paperless-data"
    fs_type: "ext4"
    mount_options: "defaults,nofail"
  - disk_gb: 200
    pve_storage: "local-pve-rpool"
    mount_path: "/media/immich-data"
    fs_type: "ext4"
    mount_options: "defaults,nofail"

# enable_autoupdate: false

add_docker_users:
  - "captain"

add_docker_reverse_proxy_bindings:
  - port: 8000
    hostnames:
      - "paperless.lan"
      - "paperless.vpn"
  - port: 2283
    hostnames:
      - "immich.lan"
      - "immich.vpn"

add_paperless_owner_user: "captain"
add_paperless_time_zone: "Europe/Berlin"
add_paperless_ocr_language: "deu"

add_immich_owner_user: "captain"
add_immich_time_zone: "Europe/Berlin"

add_admin_scripts_user: "captain"

add_restic_client_repositories:
  - name: "paperless"
    path: "/media/paperless-data/export"
    repository: "rest:http://{rest_username}:{rest_password}@backup.lan:8000/{rest_username}/paperless"
    backup_pre_command: "/usr/local/bin/paperless-export-backup"
    backup_schedule_enabled: false
  - name: "immich"
    path: "/media/immich-data/library"
    repository: "rest:http://{rest_username}:{rest_password}@backup.lan:8000/{rest_username}/immich"
    backup_schedule_enabled: false

host_users:
  - name: "captain"
    description: "container service account"
    groups:
      - sudo
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICYIQ2DpOGZ7q8FwbYfuJvDzaO0LYE3qrrD5q7qb0pKD lars@co3d.eu"

# vault.yml:
# host_user_passwords:
#   captain: "SECRET_VALUE_HERE"
#
# add_immich_db_password: "SECRET_VALUE_HERE"
# add_paperless_db_password: "SECRET_VALUE_HERE"
# add_paperless_secret_key: "SECRET_VALUE_HERE"
#
# add_restic_client_repository_credentials:
#   paperless:
#     rest_username: "SECRET_VALUE_HERE"
#     rest_password: "SECRET_VALUE_HERE"
#     repository_password: "SECRET_VALUE_HERE"
#   immich:
#     rest_username: "SECRET_VALUE_HERE"
#     rest_password: "SECRET_VALUE_HERE"
#     repository_password: "SECRET_VALUE_HERE"
