---
add_docker_prerequisite_packages:
  - ca-certificates
  - curl

add_docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - haproxy

add_docker_keyring_dir: /etc/apt/keyrings
add_docker_keyring_path: "{{ add_docker_keyring_dir }}/docker.asc"
add_docker_repo_path: /etc/apt/sources.list.d/docker.list
add_docker_repo_url: https://download.docker.com/linux/ubuntu
add_docker_repo_gpg_url: "{{ add_docker_repo_url }}/gpg"

add_docker_users: []
add_docker_reverse_proxy_bindings: []
add_docker_reverse_proxy_enabled: "{{ add_docker_reverse_proxy_bindings | length > 0 }}"
add_docker_reverse_proxy_bind_port: 80
add_docker_reverse_proxy_tls_bind_port: 443
add_docker_reverse_proxy_backend_host_default: 127.0.0.1
add_docker_reverse_proxy_ca_cert_src: "{{ playbook_dir }}/../context/homelab-ca/ca.crt"
add_docker_reverse_proxy_tls_cert_name: "{{ inventory_hostname }}"
add_docker_reverse_proxy_tls_cert_src: >-
  {{
    playbook_dir ~ '/../context/homelab-ca/client/' ~
    add_docker_reverse_proxy_tls_cert_name ~ '.crt'
  }}
add_docker_reverse_proxy_tls_key_src: >-
  {{
    playbook_dir ~ '/../context/homelab-ca/client/' ~
    add_docker_reverse_proxy_tls_cert_name ~ '.key'
  }}
add_docker_haproxy_service_name: haproxy
add_docker_haproxy_config_path: /etc/haproxy/haproxy.cfg
add_docker_haproxy_cert_dir: /etc/haproxy/certs
add_docker_haproxy_tls_pem_path: "{{ add_docker_haproxy_cert_dir }}/{{ add_docker_reverse_proxy_tls_cert_name }}.pem"
add_docker_host_ca_cert_path: /usr/local/share/ca-certificates/homelab-ca.crt

add_docker_admin_scripts_service_groups:
  - key: "docker"
    label: "docker"
    status_units:
      - docker.service
    start_enable_units:
      - docker.service
    start_start_units: []
    stop_disable_units: []
    stop_stop_units: []
  - key: "docker-proxy"
    label: "docker reverse proxy"
    status_units:
      - "{{ add_docker_haproxy_service_name }}.service"
    start_enable_units:
      - "{{ add_docker_haproxy_service_name }}.service"
    start_start_units: []
    stop_disable_units:
      - "{{ add_docker_haproxy_service_name }}.service"
    stop_stop_units:
      - "{{ add_docker_haproxy_service_name }}.service"
