---
all:
  children:
    proxmox:
      hosts:
        n2:
          ansible_host: 192.168.178.6
          ansible_user: root
        n5:
          ansible_host: 192.168.178.5
          ansible_user: root
    vm:
      hosts:
        restic1:
