---
add_ansible_execution_packages:
  - ca-certificates
  - git
  - openssh-client
  - python3-pip
  - python3-venv
  - sshpass
  - xorriso

add_ansible_execution_repo_owner: "{{ ansible_user }}"
add_ansible_execution_repo_group: "{{ add_ansible_execution_repo_owner }}"
add_ansible_execution_repo_dir_name: homelab
add_ansible_execution_repo_url: "https://github.com/rocketpie/homelab.git"
add_ansible_execution_repo_version: main

add_ansible_execution_install_powershell: true
add_ansible_execution_install_uv: true
add_ansible_execution_copy_ssh_key: false
add_ansible_execution_ssh_private_key_source: >-
  {{ ansible_admin_ssh_private_key_file }}
add_ansible_execution_ssh_public_key_source: >-
  {{ ansible_admin_ssh_private_key_file }}.pub
add_ansible_execution_prefill_vault_templates: true
add_ansible_execution_autoinstall_server_script: >-
  srv/Start-AutoInstallServer-{{ inventory_hostname }}.sh
