---
# ../ansbible/inventories/homelab/group_vars/all.yml
proxmox_api_host: "192.168.178.6"      # pick ONE reachable node (n2 or n5)
proxmox_api_user: "ansible@pve"

# API Token auth (recommended)
proxmox_api_token_id: "ansible-token"
proxmox_api_token_secret: "BOOTSTRAP_TOKEN_SECRET_HERE"

# If you're using the default self-signed cert, keep false
proxmox_verify_ssl: false
