vmid: 22001
proxmox_node: "n2"

proxmox_ostype: "l26"
proxmox_iso_filename: "ubuntu-24.04.4-live-server-amd64-autoinstall.iso"

cores: 2
memory_mb: 2048
os_disk_gb: 20

extra_disks:
  - disk_gb: 50
    pve_storage: "local-pve-rpool"
    mount_path: "/media/backups"
    fs_type: "ext4"
    mount_options: "defaults,nofail"

host_users:
  - name: "archivar"
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICYIQ2DpOGZ7q8FwbYfuJvDzaO0LYE3qrrD5q7qb0pKD lars@co3d.eu"

# vault.yml:
# host_user_passwords:
#   archivar: "USER_PASSWORD_HERE"
