set_proxmox_vm_hardware_manage_replication: true
set_proxmox_vm_hardware_prefer_live_migration: true
set_proxmox_vm_hardware_replication_schedule_default: "*/15"
set_proxmox_vm_hardware_migrate_retries: 120
set_proxmox_vm_hardware_migrate_delay: 60
