---
add_restic_retention_packages:
  - restic

add_restic_retention_service_user: "{{ add_restic_server_service_user | default('root') }}"
add_restic_retention_service_group: "{{ add_restic_retention_service_user }}"

add_restic_retention_binary_path: /usr/bin/restic
add_restic_retention_root_dir: "{{ add_restic_server_data_dir }}"
add_restic_retention_config_dir: /etc/restic-retention
add_restic_retention_env_dir: "{{ add_restic_retention_config_dir }}/repos.d"
add_restic_retention_script_path: /usr/local/bin/restic-retention

add_restic_retention_service_name: restic-retention.service
add_restic_retention_service_unit_path: >-
  /etc/systemd/system/{{ add_restic_retention_service_name }}
add_restic_retention_timer_name: restic-retention.timer
add_restic_retention_timer_unit_path: >-
  /etc/systemd/system/{{ add_restic_retention_timer_name }}
add_restic_retention_timer_on_calendar: daily
add_restic_retention_timer_randomized_delay_sec: 30m

add_restic_retention_repositories: []
add_restic_retention_repository_passwords: {}

add_restic_retention_admin_scripts_service_groups:
  - key: "restic-retention"
    label: "restic retention"
    status_units:
      - "{{ add_restic_retention_service_name }}"
      - "{{ add_restic_retention_timer_name }}"
    start_enable_units:
      - "{{ add_restic_retention_timer_name }}"
    start_start_units: []
    stop_disable_units:
      - "{{ add_restic_retention_timer_name }}"
    stop_stop_units:
      - "{{ add_restic_retention_service_name }}"

add_restic_retention_admin_scripts_extra_scripts: []
